### ISSUE TITLE
bug for R >= 4.0

### ISSUE THREAD

**Issue by johannesgeibel** [tpook92/MoBPS#1]
HI Torsten,
since R 4.0, matrix has class "matrix" and "array", resulting in warnings, e.g.:
```{r} 
temp <- MoBPS::founder.simulation(nindi = 100,
                                  sex.quota = 0.5,
                                  nsnp = 100,
                                  n.gen = 2)
temp <- creating.diploid(dataset = temp)
```

> Warnmeldung:
> In if (class(dataset) == "haplomatrix") { :
>   Bedingung hat Länge > 1 und nur das erste Element wird benutzt

```
"haplomatrix" %in% class(dataset)
```
should help

**Comment by tpook92** [comment]
Dear Johannes,
thanks for reporting the issue. The if statements corrected in the newest version of MoBPS (v1.6.37) - simulation results were not affected by this warning.
Best regards Torsten
