### ISSUE TITLE
keep contig info from vcf import

### ISSUE THREAD

**Issue by johannesgeibel** [tpook92/MoBPS#3]
By now, the contig length for a vcf output is the position of the last marker on a chromosome. In case of an imported map (e.g. from a vcf), the sequence dictionary info should be tracked if possible and the output should match the input to ensure compatibility with default software that relies on indexed reference genomes.

**Comment by tpook92** [comment]
Your code has been merged to the main branch and this feature is now available via the VariantAnnotation package.
